# .github/workflows/test.yml
name: Test with Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Gradle Tests
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:3.141.59
        options: >-
          --health-cmd="curl -f http://localhost:4444/wd/hub || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 4444:4444

    container:
      image: gradle:8.13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          cd tests
          gradle test
